site_name: Docs
nav:
    - Home: index.md
    - About: about.md

theme:
  logo: assets/logo.svg
  favicon: assets/favicon.svg

  name: material

  font:
    text: Atkinson Hyperlegible
    code: Roboto Mono
  
  palette: 

    # Palette toggle for light mode
    - scheme: default
      primary: black
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

    

extra:
  generator: false

copyright: Copyright &copy; 2022 Caesar
    # # Palette toggle for light mode
      

